{
  "customers": [
    {
      "area": "Khuzam",
      "address": "plot no 1 ",
      "last_name": "CHARAN",
      "rate_code": "Ajman",
      "street_name": "Al Shaikh Street",
      "contact_number": "0552573946",
      "serialNo": "6",
      "alter_Contact_Number": "85654875454",
      "id": "0d2dd08e-61de-4283-a2b3-c5476e73871b",
      "first_name": "MITHU",
      "email": "CHARANMITHU78@yahoo.com",
      "apartment": "Apartment no 2",
      "Password": "%%%%eteW7M5WYJ/MwUlrsUFkWQ==%%%%"
    },
    {
      "area": "",
      "address": "",
      "last_name": "",
      "rate_code": "Ajman",
      "street_name": "",
      "contact_number": "",
      "serialNo": "111",
      "alter_Contact_Number": "",
      "id": "100",
      "first_name": "",
      "email": "j@gmail.com",
      "apartment": "",
      "Password": ""
    },
    {
      "area": "",
      "address": "",
      "last_name": "",
      "rate_code": "Ajman",
      "street_name": "",
      "contact_number": "",
      "serialNo": "112",
      "alter_Contact_Number": "",
      "id": "101",
      "first_name": "",
      "email": "a@gmail.com",
      "apartment": "",
      "Password": ""
    },
    {
      "area": "",
      "address": "",
      "last_name": "",
      "rate_code": "Ajman",
      "street_name": "",
      "contact_number": "",
      "serialNo": "113",
      "alter_Contact_Number": "",
      "id": "102",
      "first_name": "",
      "email": "a@gmail.com",
      "apartment": "",
      "Password": ""
    },
    {
      "area": "",
      "address": "",
      "last_name": "",
      "rate_code": "Ras Al Khaimah",
      "street_name": "",
      "contact_number": "",
      "serialNo": "114",
      "alter_Contact_Number": "",
      "id": "103",
      "first_name": "",
      "email": "random@gmail.com",
      "apartment": "",
      "Password": ""
    },
    {
      "area": "",
      "address": "",
      "last_name": "",
      "rate_code": "Ras Al Khaimah",
      "street_name": "",
      "contact_number": "",
      "serialNo": "115",
      "alter_Contact_Number": "",
      "id": "104",
      "first_name": "",
      "email": "j@gmail",
      "apartment": "",
      "Password": ""
    },
    {
      "area": "",
      "address": "",
      "last_name": "",
      "rate_code": "Ras Al Khaimah",
      "street_name": "",
      "contact_number": "",
      "serialNo": "116",
      "alter_Contact_Number": "",
      "id": "105",
      "first_name": "",
      "email": "random234@gmail.com",
      "apartment": "",
      "Password": ""
    },
    {
      "area": "",
      "address": "",
      "last_name": "",
      "rate_code": "Ajman",
      "street_name": "",
      "contact_number": "",
      "serialNo": "117",
      "alter_Contact_Number": "",
      "id": "106",
      "first_name": "",
      "email": "Guest@gmail.com",
      "apartment": "",
      "Password": ""
    },
    {
      "area": "a",
      "address": "a",
      "last_name": "Bilal",
      "rate_code": "Sharjah",
      "street_name": "a",
      "contact_number": "07498160645",
      "serialNo": "126",
      "alter_Contact_Number": "",
      "id": "115",
      "first_name": "Ansari",
      "email": "mohdbilal2870@gmail.com",
      "apartment": "a",
      "Password": "Bilal@cr7"
    },
    {
      "area": "Jebal ali",
      "address": "Shaikh Zayed road",
      "last_name": "Bagbannn",
      "rate_code": "Dubai",
      "street_name": "Shaikh Zayed Road",
      "contact_number": "8080392095",
      "serialNo": "87",
      "alter_Contact_Number": "222222222",
      "id": "77",
      "first_name": "Ikram",
      "email": "bagbanikram@gmail.com",
      "apartment": "123",
      "Password": "121"
    },
    {
      "area": "Jebal ali",
      "address": "Mumbai",
      "last_name": "Ansari",
      "rate_code": "Ajman",
      "street_name": "Thane",
      "contact_number": "7039187927",
      "serialNo": "88",
      "alter_Contact_Number": "4563146565",
      "id": "78",
      "first_name": "Sidra",
      "email": "admin",
      "apartment": "Rose Villah Apt",
      "Password": "P@ssw0rd"
    },
    {
      "area": "Jebal ali",
      "address": "Mumbai",
      "last_name": "Jaddi",
      "rate_code": "Ras Al Khaimah",
      "street_name": "Thane",
      "contact_number": "+918080392095",
      "serialNo": "89",
      "alter_Contact_Number": "2223444433",
      "id": "79",
      "first_name": "Ammaarah",
      "email": "ammarah@gmail.com",
      "apartment": "Rose Villah Apt",
      "Password": "Ammarah@123"
    },
    {
      "area": "",
      "address": "mount rabia",
      "last_name": "jaddi",
      "rate_code": "Ajman",
      "street_name": "",
      "contact_number": "2134354657",
      "serialNo": "101",
      "alter_Contact_Number": "",
      "id": "90",
      "first_name": "Ammaarah",
      "email": "ammu123@gmail.com",
      "apartment": "213",
      "Password": "1234"
    },
    {
      "area": "",
      "address": "mount rabia",
      "last_name": "jaddi",
      "rate_code": "Ajman",
      "street_name": "",
      "contact_number": "",
      "serialNo": "106",
      "alter_Contact_Number": "",
      "id": "95",
      "first_name": "ammaarah",
      "email": "ammaarahjaddi@gmail.com",
      "apartment": "",
      "Password": "123"
    },
    {
      "area": "",
      "address": "",
      "last_name": "",
      "rate_code": "Ajman",
      "street_name": "",
      "contact_number": "",
      "serialNo": "110",
      "alter_Contact_Number": "",
      "id": "99",
      "first_name": "",
      "email": "jannatiqbalsk1@gmail.com",
      "apartment": "",
      "Password": ""
    },
    {
      "area": "qaemar",
      "address": "",
      "last_name": "fatima",
      "rate_code": "Dubai",
      "street_name": "",
      "contact_number": "",
      "serialNo": "90",
      "alter_Contact_Number": "",
      "id": "adef29db-b227-47a9-a355-fc10b59d2f17",
      "first_name": "sana",
      "email": "sanafatima@gmail.com",
      "apartment": "",
      "Password": ""
    },
    {
      "area": "udated Area",
      "address": "updated Address",
      "last_name": "Doe",
      "rate_code": "Code",
      "street_name": "Some Street",
      "contact_number": "1234567890",
      "serialNo": "1201",
      "alter_Contact_Number": "333333333",
      "id": "11221",
      "first_name": "John",
      "email": "john.doe@example.com",
      "apartment": "456",
      "Password": "12345"
    }
  ]
}