export const product = [
  {
    productId: 1,
    name: 'ASIAN KURTA',
    cat: 'men',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571464823.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 36, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 47, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 60, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 40, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 50, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 17, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 75, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 600, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 500, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 60, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 45, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 2,
    name: 'COAT',
    cat: 'men',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1567877450.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 41, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 66, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 3,
    name: 'JACKET',
    cat: 'men',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1567877926.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 35, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 4,
    name: 'SAFARI SUIT',
    cat: 'men',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1575731337.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 17, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 5,
    name: 'UNDERSHIRT',
    cat: 'men',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571467753.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 55, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 6,
    name: 'KANDURA ',
    cat: 'men',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571468420.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 43, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 7,
    name: 'WAISTCOAT',
    cat: 'men',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571467948.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 8,
    name: 'LEATHER JACKET',
    cat: 'men',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571468674.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 29,
    name: 'SWEATER',
    cat: 'men',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571469375.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 9,
    name: 'ABAYA',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1567876758.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 10,
    name: 'ASIAN ETHNIC WEAR',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571473993.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 11,
    name: 'ASIAN SHIRT FOR',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571471398.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 12,
    name: 'BLOUSE',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571469849.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 13,
    name: 'EMBROIDERED JALABIYA ',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571471130.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 14,
    name: 'EMBROIDERED SCARF',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1567877173.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 15,
    name: 'LONG DRESS ',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571470012.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 16,
    name: 'JUMPSUIT ',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571471291.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 17,
    name: 'LONG SKIRT',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571474466.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 18,
    name: 'NIGHTIE',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571473692.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 19,
    name: 'SHORT DRESS',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571470152.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 20,
    name: 'TRADITIONAL ASIAN DRESS',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571474204.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 21,
    name: 'WEDDING DRESS',
    cat: 'women',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1611492848.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 22,
    name: 'BABY FROCK',
    cat: 'kid',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571474991.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 17, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 23,
    name: 'CAPES',
    cat: 'kid',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1663577969.png',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 24,
    name: 'PULLOVER ',
    cat: 'kid',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1663578123.png',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 25,
    name: 'PYJAMA TOP',
    cat: 'kid',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1595321305.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 26,
    name: 'STUFFED TOYS',
    cat: 'kid',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1663052035.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 27,
    name: 'UNDERPANT ',
    cat: 'kid',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1567867733.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 250, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
  {
    productId: 28,
    name: 'KANDURA ',
    cat: 'kid',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1567867246.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 200, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 200, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
];
export const services = [
  {
    serviceId: 1,
    serviceName: 'DryClean',
    serviceImg: 'http://localhost:8081/assets/images/DryClean.png',
  },
  {
    serviceId: 2,
    serviceName: 'Laundry',
    serviceImg: 'http://localhost:8081/assets/images/Laundry.png',
  },
  {
    serviceId: 3,
    serviceName: 'Press',
    serviceImg: 'http://localhost:8081/assets/images/Iron.png',
  },
];

export const delveryTime = [
  {delveryId: 1, title: 'Standard (48 hrs)'},
  {delveryId: 2, title: 'Express (24 hrs)'},
  {delveryId: 3, title: 'Same Day (12 hrs)'},
];

export const cartItems = [
  {
    productId: 1,
    name: 'ASIAN KURTA',
    cat: 'men',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1571464823.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 36, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 47, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 40, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 75, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 600, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 500, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 60, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 45, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]
  },
  {
    productId: 2,
    name: 'COAT',
    cat: 'men',
    img: 'https://modernlaundry.net/admin/uploads/item/ITEM_1567877450.jpg',
    pricing: [
      {
        'Ras-Al-Khaima': [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Sharjha: [
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
        Dubai: [
          {serviceId: 1, serviceName: 'Dryclean', price: 41, delveryTypeId: 2,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 2,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 2,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 66, delveryTypeId: 1,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 1,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 1,selected : false},
          {serviceId: 1, serviceName: 'Dryclean', price: 21, delveryTypeId: 3,selected : false},
          {serviceId: 2, serviceName: 'Laundry', price: 25, delveryTypeId: 3,selected : false},
          {serviceId: 3, serviceName: 'Press', price: 50, delveryTypeId: 3,selected : false},
        ],
      },
    ],
    delveryTypeFormat :[{title : "Folded", selected : false},{title : "Hanger", selected : false}]

  },
];
