const pr = [
    {
      pricing: [
        {
          item: "47",
          service: "Press",
          price: "0.00",
          deliveryType: "3",
          emirate_id: "5",
        },
        {
          item: "37",
          service: "Dryclean",
          price: "42.00",
          deliveryType: "2",
          emirate_id: "5",
        },
        {
          item: "7",
          service: "Dryclean",
          price: "4.788",
          deliveryType: "1",
          emirate_id: "1",
        },
        {
          item: "37",
          service: "Laundry",
          price: "42.00",
          deliveryType: "2",
          emirate_id: "5",
        },
        {
          item: "117",
          service: "Press",
          price: "25.20",
          deliveryType: "2",
          emirate_id: "5",
        },
        {
          item: "37",
          service: "Dryclean",
          price: "21.00",
          deliveryType: "1",
          emirate_id: "5",
        },
        {
          item: "27",
          service: "Press",
          price: "6.30",
          deliveryType: "3",
          emirate_id: "5",
        },
        {
          item: "7",
          service: "Press",
          price: "9.576",
          deliveryType: "3",
          emirate_id: "1",
        },
        {
          item: "117",
          service: "Dryclean",
          price: "66.15",
          deliveryType: "3",
          emirate_id: "5",
        },
        {
          item: "75",
          service: "Press",
          price: "0",
          deliveryType: "1",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "117",
          service: "Laundry",
          price: "50.40",
          deliveryType: "3",
          emirate_id: "5",
        },
        {
          item: "47",
          service: "Laundry",
          price: "18.90",
          deliveryType: "3",
          emirate_id: "5",
        },
        {
          item: "27",
          service: "Press",
          price: "4.20",
          deliveryType: "2",
          emirate_id: "5",
        },
        {
          item: "75",
          service: "Dryclean",
          price: "11.969999999999999",
          deliveryType: "1",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "7",
          service: "Laundry",
          price: "19.152",
          deliveryType: "3",
          emirate_id: "1",
        },
        {
          item: "47",
          service: "Dryclean",
          price: "18.90",
          deliveryType: "3",
          emirate_id: "5",
        },
        {
          item: "27",
          service: "Laundry",
          price: "18.90",
          deliveryType: "3",
          emirate_id: "5",
        },
        {
          item: "47",
          service: "Dryclean",
          price: "12.60",
          deliveryType: "2",
          emirate_id: "5",
        },
        {
          item: "7",
          service: "Laundry",
          price: "9.576",
          deliveryType: "2",
          emirate_id: "1",
        },
        {
          item: "75",
          service: "Press",
          price: "0",
          deliveryType: "3",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "117",
          service: "Dryclean",
          price: "44.10",
          deliveryType: "2",
          emirate_id: "5",
        },
        {
          item: "27",
          service: "Laundry",
          price: "6.30",
          deliveryType: "1",
          emirate_id: "5",
        },
        {
          item: "47",
          service: "Laundry",
          price: "6.30",
          deliveryType: "1",
          emirate_id: "5",
        },
        {
          item: "117",
          service: "Laundry",
          price: "33.60",
          deliveryType: "2",
          emirate_id: "5",
        },
        {
          item: "27",
          service: "Press",
          price: "2.10",
          deliveryType: "1",
          emirate_id: "5",
        },
        {
          item: "117",
          service: "Press",
          price: "12.60",
          deliveryType: "1",
          emirate_id: "5",
        },
        {
          item: "7",
          service: "Laundry",
          price: "4.788",
          deliveryType: "1",
          emirate_id: "1",
        },
        {
          item: "27",
          service: "Dryclean",
          price: "6.30",
          deliveryType: "1",
          emirate_id: "5",
        },
        {
          item: "47",
          service: "Dryclean",
          price: "6.30",
          deliveryType: "1",
          emirate_id: "5",
        },
        {
          item: "117",
          service: "Press",
          price: "37.80",
          deliveryType: "3",
          emirate_id: "5",
        },
        {
          item: "37",
          service: "Dryclean",
          price: "63.00",
          deliveryType: "3",
          emirate_id: "5",
        },
        {
          item: "47",
          service: "Press",
          price: "0.00",
          deliveryType: "2",
          emirate_id: "5",
        },
        {
          item: "117",
          service: "Dryclean",
          price: "22.05",
          deliveryType: "1",
          emirate_id: "5",
        },
        {
          item: "37",
          service: "Laundry",
          price: "63.00",
          deliveryType: "3",
          emirate_id: "5",
        },
        {
          item: "47",
          service: "Press",
          price: "0.00",
          deliveryType: "1",
          emirate_id: "5",
        },
        {
          item: "37",
          service: "Press",
          price: "31.50",
          deliveryType: "3",
          emirate_id: "5",
        },
        {
          item: "117",
          service: "Laundry",
          price: "16.80",
          deliveryType: "1",
          emirate_id: "5",
        },
        {
          item: "7",
          service: "Dryclean",
          price: "9.576",
          deliveryType: "2",
          emirate_id: "1",
        },
        {
          item: "27",
          service: "Dryclean",
          price: "18.90",
          deliveryType: "3",
          emirate_id: "5",
        },
        {
          item: "27",
          service: "Laundry",
          price: "12.60",
          deliveryType: "2",
          emirate_id: "5",
        },
        {
          item: "7",
          service: "Press",
          price: "2.394",
          deliveryType: "1",
          emirate_id: "1",
        },
        {
          item: "7",
          service: "Press",
          price: "4.788",
          deliveryType: "2",
          emirate_id: "1",
        },
        {
          item: "75",
          service: "Laundry",
          price: "23.939999999999998",
          deliveryType: "2",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "27",
          service: "Dryclean",
          price: "12.60",
          deliveryType: "2",
          emirate_id: "5",
        },
        {
          item: "37",
          service: "Laundry",
          price: "21.00",
          deliveryType: "1",
          emirate_id: "5",
        },
        {
          item: "75",
          service: "Laundry",
          price: "35.91",
          deliveryType: "3",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "75",
          service: "Press",
          price: "0",
          deliveryType: "2",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "75",
          service: "Laundry",
          price: "11.969999999999999",
          deliveryType: "1",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "7",
          service: "Dryclean",
          price: "19.152",
          deliveryType: "3",
          emirate_id: "1",
        },
        {
          item: "37",
          service: "Press",
          price: "21.00",
          deliveryType: "2",
          emirate_id: "5",
        },
        {
          item: "47",
          service: "Laundry",
          price: "12.60",
          deliveryType: "2",
          emirate_id: "5",
        },
        {
          item: "75",
          service: "Dryclean",
          price: "23.939999999999998",
          deliveryType: "2",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "37",
          service: "Press",
          price: "10.50",
          deliveryType: "1",
          emirate_id: "5",
        },
        {
          item: "75",
          service: "Dryclean",
          price: "35.91",
          deliveryType: "3",
          emirate_id: "Ras Al Khaimah",
        },
      ],
    },
    {
      pricing: [
        {
          item: "83",
          service: "Press",
          price: "70.81452",
          deliveryType: "3",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "83",
          service: "Laundry",
          price: "41.30847",
          deliveryType: "1",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "83",
          service: "Laundry",
          price: "47.20968",
          deliveryType: "2",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "83",
          service: "Dryclean",
          price: "82.61694",
          deliveryType: "2",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "83",
          service: "Press",
          price: "23.60484",
          deliveryType: "1",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "83",
          service: "Laundry",
          price: "123.92541000000003",
          deliveryType: "3",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "83",
          service: "Laundry",
          price: "82.61694",
          deliveryType: "2",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "83",
          service: "Dryclean",
          price: "41.30847",
          deliveryType: "1",
          emirate_id: "Ras Al Khaimah",
        },
        {
          item: "83",
          service: "Dryclean",
          price: "123.92541000000003",
          deliveryType: "3",
          emirate_id: "Ras Al Khaimah",
        },
      ],
    },
    {
      pricing: [
        {
          item: "13",
          service: "Press",
          price: "11.969999999999999",
          deliveryType: "1",
          emirate_id: "1",
        },
        {
          item: "13",
          service: "Laundry",
          price: "0",
          deliveryType: "2",
          emirate_id: "1",
        },
        {
          item: "130",
          service: "Dryclean",
          price: "5.50",
          deliveryType: "2",
          emirate_id: "Dubai",
        },
        {
          item: "13",
          service: "Laundry",
          price: "0",
          deliveryType: "3",
          emirate_id: "1",
        },
        {
          item: "13",
          service: "Dryclean",
          price: "95.75999999999999",
          deliveryType: "3",
          emirate_id: "1",
        },
        {
          item: "13",
          service: "Laundry",
          price: "0",
          deliveryType: "1",
          emirate_id: "1",
        },
        {
          item: "13",
          service: "Dryclean",
          price: "19.95",
          deliveryType: "1",
          emirate_id: "1",
        },
        {
          item: "13",
          service: "Dryclean",
          price: "63.84",
          deliveryType: "2",
          emirate_id: "1",
        },
        {
          item: "133",
          service: "Dryclean",
          price: "63.84",
          deliveryType: "2",
          emirate_id: "1",
        },
        {
          item: "13",
          service: "Press",
          price: "59.85",
          deliveryType: "3",
          emirate_id: "1",
        },
        {
          item: "13",
          service: "Press",
          price: "39.9",
          deliveryType: "2",
          emirate_id: "1",
        },
      ],
    },
  ];